name: Deploy App to Code Engine

on:
  push:
    branches:
      - main

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Deploy Application to Code Engine
      uses: ibm/code-engine-github-action@v1
      with:
        api-key: 'g6P_sEpvcMKhVPYtM37rMz2t88dKZ8oNAvwv9i26KBML'
        resource-group: 'Technonest-GM'
        region: 'us-south'
        project: 'ce-project-Appbogado'
        component: 'app'
        name: 'appbogados'
        build-source: './appAbogados'
